jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 3
    matrix:
      Node.js 6:
        node_version: 6.x
      Node.js 8:
        node_version: 8.x
      Node.js 10:
        node_version: 10.x

  steps:
  - template: azure-pipelines/steps.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 3
    matrix:
      Node.js 6:
        node_version: 6.x
      Node.js 8:
        node_version: 8.x
      Node.js 10:
        node_version: 10.x

  steps:
  - template: azure-pipelines/steps.yml

