  - task: NodeTool@0
    inputs:
      version: $(node_version)
    displayName: 'Install Node.js $(node_version)'  

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      node --version
      npm --version
    displayName: 'Output node and npm version'

  - script: |
      npm test
    condition: or(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['Agent.OS'], 'Darwin'))
    displayName: 'npm test'

  - script: |
      npm run cover # includes `npm test`
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'npm run cover'    